export { default as Contract } from "./Contract.vue"
export { default as Contracts } from "./Contracts.vue"
export { default as ContractUpload } from "./ContractUpload.vue"
export { default as ContractExecute } from "./ContractExecute.vue"
export { default as ContractInstantiate } from "./ContractInstantiate.vue"
export { default as ContractQuery } from "./ContractQuery.vue"
